### ISSUE TITLE
"preferredFormat" property does not return correct formats

### ISSUE THREAD

**Issue by Luiz-N** [RSSchermer/ember-spectrum-color-picker#3]
If I feed the picker an array of RGBA color values it will correctly interpret the colors however will later feed them back as a hex value even if the color was not changed.

**Comment by RSSchermer** [comment]
I suspect the problems is [these lines](https://github.com/RSSchermer/ember-spectrum-color-picker/blob/0.0.4/addon/components/spectrum-color-picker.js#L81-83):

```js
var updateFunction = function(newColor) {
  self.set('color', newColor.toHexString());
};
```
I'll look into it.

**Comment by RSSchermer** [comment]
I changed the above code to respect the specified `preferredFormat` or the format inferred from the initial value as of 0.1.0. Let me know if that fixes your problem.

**Comment by Luiz-N** [comment]
That worked! The only caveat is that it will convert a rgba with an "a" value of 1 to it's basic rgb equivalent. so 'rgba(51,160,44,1)' gets returned/updated as 'rgb(51,160,44)' which is the same color however if you're expecting an rgba later for color manipulation it can screw things up.

Probably still fair to close the issue though.

**Comment by RSSchermer** [comment]
Thanks for the feedback! Rgba with an alpha of 1 getting converted into the rgb value is would be an issue with spectrum.js itself I think. Anyway, thanks again for bringing up this issue!
