### ISSUE TITLE
bug in color spectrum color picker.. missing </span>

### ISSUE THREAD

**Issue by beastmst** [RSSchermer/ember-spectrum-color-picker#36]
that is a bug in spectrum color picker, causing all the pallet stack on each other...

can you please fix?

https://github.com/bgrins/spectrum/issues/563

**Comment by RSSchermer** [comment]
I've released 0.10.1 which updates the spectrum version to 1.8.1, could you confirm this resolves your issue?

**Comment by beastmst** [comment]
yeah... fixed
